### ISSUE TITLE
Examples Folder

### ISSUE THREAD

**Issue by ghost** [dzarezenko/poloniex-api#1]
I hate to nit-pick but theres no 'examples' folder as per the 'usage' section of the read-me. It would be super helpful if you could upload that. Thanks!

**Comment by dzarezenko** [comment]
@dogpatchmedia I have added ticker example to GitHub. If you need more examples - simply describe list of needed examples. I will add them step-by-step by request.

**Comment by dzarezenko** [comment]
Waiting for separate issue with required examples list.
