### ISSUE TITLE
How I get ticker based BTC rate value in USD ?

### ISSUE THREAD

**Issue by juniorspecialist** [dzarezenko/poloniex-api#4]
Hi!
When I run code:

$tickerRate = Poloniex::getTickerBTCRate();

I  get "Warning: file_get_contents(https://poloniex.com/public?command=returnTicker): failed to open stream: HTTP request failed! HTTP/1.1 403 Forbidden in "
How to fix ?
In the class Request,  I setting params - apiKey, apiSecret. I getting data from personal page of site, but I have problem.

**Comment by dzarezenko** [comment]
Hi,
I have checked right now and all works for me.

My code example:
```
use conf\Config;

use poloniex\api\Poloniex;

error_reporting(E_ALL);
ini_set('display_errors', 1);

require_once(dirname(__FILE__) . "/../../../vendor/autoload.php");

$tickerRate = Poloniex::getTickerBTCRate();
var_dump($tickerRate);
```

This method from public API methods list, so you may not to set API keys at all if you use just this one method.

**Comment by juniorspecialist** [comment]
My code:
ini_set('error_reporting', E_ALL);
ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
require '../vendor/autoload.php';
use poloniex\api\Poloniex;
$tickerRate = Poloniex::getTickerBTCRate();
var_dump($tickerRate);

but I have 403 error, this my screenshot https://s.nimbus.everhelper.me/share/1238995/tr2ykl0uweznr1tkcnly

what could be the problem ?
What rights can be ? If sending to public api, do not need api_key and secret.

**Comment by dzarezenko** [comment]
Hi,
your code works for me as well, so maybe you have some server/PHP configuration problems.

You can fix this problems or replace `file_get_contents` based request functionality with cURL and make pull request to my repo. I have plans to do this in future when have time.

**Comment by juniorspecialist** [comment]
Problem was in my IP, I using proxy and CURL and no problem!
