### ISSUE TITLE
Testnet support ??

### ISSUE THREAD

**Issue by Govind13100** [dzarezenko/poloniex-api#6]
Is there any testnet support ??? I want to generate address and want to transfer test tether on that address from external source??

is this possible ???

**Comment by dzarezenko** [comment]
If you mean (ropsten or some other testnet) - no, Poloniex works only with real crypto-currencies.

**Comment by Govind13100** [comment]
okay thanks for your reply.

If possible then please suggest something on this 

I want to do tether (USDT) transfer i.e create usdt wallet and create transaction.

 did you know any other API or any other thing that could help to implement USDT????

**Comment by ejrhe** [comment]
Do you support Testnet3 BTC?
